--[[

The MIT License (MIT)

Copyright (c) 2015 ediiknorand

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

--]]

local CONST  = {}

-- Homunculus ID
CONST.LIF              =  1
CONST.AMISTR           =  2
CONST.FILIR            =  3
CONST.VANILMIRTH       =  4

CONST.LIF2             =  5
CONST.AMISTR2          =  6
CONST.FILIR2           =  7
CONST.VANILMIRTH2      =  8

CONST.LIF_H            =  9
CONST.AMISTR_H         = 10
CONST.FILIR_H          = 11
CONST.VANILMIRTH_H     = 12

CONST.LIF_H2           = 13
CONST.AMISTR_H2        = 14
CONST.FILIR_H2         = 15
CONST.VANILMIRTH_H2    = 16

CONST.EIRA             = 48
CONST.BAYERI           = 49
CONST.SERA             = 50
CONST.DIETER           = 51
CONST.ELEANOR          = 52

-- Mercenary ID
CONST.MARCHER01        = 17
CONST.MARCHER02        = 18
CONST.MARCHER03        = 19
CONST.MARCHER04        = 20
CONST.MARCHER05        = 21
CONST.MARCHER06        = 22
CONST.MARCHER07        = 23
CONST.MARCHER08        = 24
CONST.MARCHER09        = 25
CONST.MARCHER10        = 26

CONST.MLANCER01        = 27
CONST.MLANCER02        = 28
CONST.MLANCER03        = 29
CONST.MLANCER04        = 30
CONST.MLANCER05        = 31
CONST.MLANCER06        = 32
CONST.MLANCER07        = 33
CONST.MLANCER08        = 34
CONST.MLANCER09        = 35
CONST.MLANCER10        = 36

CONST.MSWORDMAN01      = 37
CONST.MSWORDMAN02      = 38
CONST.MSWORDMAN03      = 39
CONST.MSWORDMAN04      = 40
CONST.MSWORDMAN05      = 41
CONST.MSWORDMAN06      = 42
CONST.MSWORDMAN07      = 43
CONST.MSWORDMAN08      = 44
CONST.MSWORDMAN09      = 45
CONST.MSWORDMAN10      = 46

CONST.MUNKNOWN         = 100
CONST.MWILDROSE        = 101
CONST.MDOPPELGANGER    = 102
CONST.MALICE           = 103
CONST.MMIMIC           = 104
CONST.MDISGUISE        = 105
CONST.MGM              = 106
CONST.MPENGINEER       = 107
CONST.MISIS            = 108

-- Class ID
CONST.NOVICE           =  0
CONST.SWORDMAN         =  1
CONST.MAGE             =  2
CONST.ARCHER           =  3
CONST.ACOLYTE          =  4
CONST.MERCHANT         =  5
CONST.THIEF            =  6

CONST.KNIGHT           =  7
CONST.PRIEST           =  8
CONST.WIZARD           =  9
CONST.BLACKSMITH       = 10
CONST.HUNTER           = 11
CONST.ASSASSIN         = 12

CONST.KNIGHT_PECO      = 13 -- Peco Rider

CONST.CRUSADER         = 14
CONST.MONK             = 15
CONST.SAGE             = 16
CONST.ROGUE            = 17
CONST.ALCHEMIST        = 18
CONST.BARD             = 19
CONST.DANCER           = 20

CONST.CRUSADER_PECO    = 21 -- Peco Rider
CONST.WEDDING          = 22

CONST.SUPERNOVICE      = 23
CONST.GUNSLINGER       = 24
CONST.NINJA            = 25

CONST.XMAS             = 26 -- Costume classes
CONST.SUMMER           = 27
CONST.HANBOK           = 28
CONST.OKTOBERFEST      = 29

CONST.NOVICE_HIGH      = 4001
CONST.SWORDMAN_HIGH    = 4002
CONST.MAGE_HIGH        = 4003
CONST.ARCHER_HIGH      = 4004
CONST.ACOLYTE_HIGH     = 4005
CONST.MERCHANT_HIGH    = 4006
CONST.THIEF_HIGH       = 4007

CONST.LORD_KNIGHT      = 4008
CONST.HIGH_PRIEST      = 4009
CONST.HIGH_WIZARD      = 4010
CONST.WHITESMITH       = 4011
CONST.SNIPER           = 4012
CONST.ASSASSIN_CROSS   = 4013

CONST.LORD_KNIGHT_PECO = 4014 -- peco rider

CONST.PALADIN          = 4015
CONST.CHAMPION         = 4016
CONST.PROFESSOR        = 4017
CONST.STALKER          = 4018
CONST.CREATOR          = 4019
CONST.CLOWN            = 4020
CONST.GYPSY            = 4021

CONST.PALADIN_PECO     = 4022 -- peco rider

CONST.BABY_NOVICE      = 4023
CONST.BABY_SWORDMAN    = 4024
CONST.BABY_MAGE        = 4025
CONST.BABY_ARCHER      = 4026
CONST.BABY_ACOLYTE     = 4027
CONST.BABY_MERCHANT    = 4028
CONST.BABY_THIEF       = 4029

CONST.BABY_KNIGHT      = 4030
CONST.BABY_PRIEST      = 4031
CONST.BABY_WIZARD      = 4032
CONST.BABY_BLACKSMITH  = 4033
CONST.BABY_HUNTER      = 4034
CONST.BABY_ASSASSIN    = 4035

CONST.BABY_KNIGHT_PECO = 4036 -- peco rider

CONST.BABY_CRUSADER    = 4037
CONST.BABY_MONK        = 4038
CONST.BABY_SAGE        = 4039
CONST.BABY_ROGUE       = 4040
CONST.BABY_ALCHEMIST   = 4041
CONST.BABY_BARD        = 4042
CONST.BABY_DANCER      = 4043

CONST.BABY_CRUSADER_PECO = 4044 -- peco rider

CONST.SUPER_BABY       = 4045 -- Super Baby? ... ok
CONST.TAEKWON_KID      = 4046
CONST.TAEKWON_MASTER   = 4047
CONST.STAR_GLADIATOR   = CONST.TAEKWON_MASTER
CONST.TAEKWON_MASTER_UNION = 4048 -- Union
CONST.STAR_GLADIATOR_UNION = CONST.TAEKWON_MASTER_UNION
CONST.SOUL_LINKER      = 4049

CONST.GANGSI           = 4050
CONST.DEATH_KNIGHT     = 4051
CONST.DARK_COLLECTOR   = 4052

CONST.RUNE_KNIGHT      = 4054
CONST.WARLOCK          = 4055
CONST.RANGER           = 4056
CONST.ARCH_BISHOP      = 4057
CONST.MECHANIC         = 4058
CONST.GUILLOTINE_CROSS = 4059

CONST.RUNE_KNIGHT_T    = 4060
CONST.WARLOCK_T        = 4061
CONST.RANGER_T         = 4062
CONST.ARCH_BISHOP_T    = 4063
CONST.MECHANIC_T       = 4064
CONST.GUILLOTINE_CROSS_T = 4065

CONST.ROYAL_GUARD      = 4066
CONST.SORCERER         = 4067
CONST.MINSTREL         = 4068
CONST.WANDERER         = 4069
CONST.SURA             = 4070
CONST.GENETIC          = 4071
CONST.SHADOW_CHASER    = 4072

CONST.ROYAL_GUARD_T    = 4073
CONST.SORCERER_T       = 4074
CONST.MINSTREL_T       = 4075
CONST.WANDERER_T       = 4076
CONST.SURA_T           = 4077
CONST.GENETIC_T        = 4078
CONST.SHADOW_CHASER_T  = 4079

CONST.RUNE_KNIGHT_DRAGON = 4080
CONST.RUNE_KNIGHT_DRAGON_T = 4081
CONST.ROYAL_GUARD_GRYPHON = 4082
CONST.ROYAL_GUARD_GRYPHON_T = 4083
CONST.RANGER_WARG      = 4084
CONST.RANGER_WARG_T    = 4085
CONST.MECHANIC_MADO    = 4086
CONST.MECHANIC_MADO_T  = 4087

CONST.BABY_RUNE_KNIGHT = 4096
CONST.BABY_WARLOCK     = 4097
CONST.BABY_RANGER      = 4098
CONST.BABY_ARCH_BISHOP = 4099
CONST.BABY_MECHANIC    = 4100
CONST.BABY_GUILLOTINE_CROSS = 4101

CONST.BABY_ROYAL_GUARD = 4102
CONST.BABY_SORCERER    = 4103
CONST.BABY_MINSTREL    = 4104
CONST.BABY_WANDERER    = 4105
CONST.BABY_SURA        = 4106
CONST.BABY_GENETIC     = 4107
CONST.BABY_SHADOW_CHASER = 4108

CONST.BABY_RUNE_KNIGHT_DRAGON = 4109
CONST.BABY_ROYAL_GUARD_GRYPHON = 4110
CONST.BABY_RANGER_WARG = 4111
CONST.BABY_MECHANIC_MADO = 4112

CONST.SUPER_NOVICE_EXPANDED = 4190
CONST.SUPER_BABY_EXPANDED = 4191

CONST.KAGEROU          = 4211
CONST.OBORO            = 4212

CONST.REBELLION        = 4215

-- Motions
CONST.MOTION_STAND       =  0
CONST.MOTION_MOVE        =  1
CONST.MOTION_ATTACK      =  2
CONST.MOTION_DEAD        =  3
CONST.MOTION_DAMAGE      =  4
CONST.MOTION_BENDDOWN    =  5
CONST.MOTION_SIT         =  6
CONST.MOTION_SKILL       =  7
CONST.MOTION_CASTING     =  8

CONST.MOTION_VULCAN      =  9
CONST.MOTION_SLEEP       = 10
CONST.MOTION_SPIRAL      = 11
CONST.MOTION_TOSS        = 12
CONST.MOTION_COUNTER     = 13

CONST.MOTION_DANCE       = 16
CONST.MOTION_PERFORM     = 17
CONST.MOTION_SHARPSHOOT  = 18
CONST.MOTION_JUMP_UP     = 19
CONST.MOTION_JUMP_FALL   = 20

CONST.MOTION_PWHIRL      = 21
CONST.MOTION_PAXE        = 22
CONST.MOTION_PROUND      = 23
CONST.MOTION_PCOUNTER    = 24

CONST.MOTION_SOULLINK    = 23

CONST.MOTION_TUMBLE      = 25
CONST.MOTION_COUNTERK    = 26
CONST.MOTION_FLYK        = 27
CONST.MOTION_BIGTOSS     = 28

CONST.MOTION_WHIRLK      = 30
CONST.MOTION_AXEK        = 31
CONST.MOTION_ROUNDK      = 32

CONST.MOTION_COMFORT     = 33
CONST.MOTION_HEAT        = 34
CONST.MOTION_NINJAGROUND = 35
CONST.MOTION_NINJAHAND   = 36
CONST.MOTION_NINJACAST   = 37
CONST.MOTION_GUNTWIN     = 38
CONST.MOTION_GUNFLIP     = 39
CONST.MOTION_GUNSHOW     = 40
CONST.MOTION_GUNCAST     = 41
CONST.MOTION_FULLBLAST   = 42

-- Commands
CONST.CMD_NONE           =  0
CONST.CMD_MOVE           =  1
CONST.CMD_STOP           =  2
CONST.CMD_ATTACK         =  3
CONST.CMD_ATTACK_AREA    =  4
CONST.CMD_PATROL         =  5
CONST.CMD_HOLD           =  6
CONST.CMD_SKILL          =  7
CONST.CMD_SKILL_AREA     =  8
CONST.CMD_FOLLOW         =  9

-- Return CONST table
return CONST
